micronaut:
  application:
    name: movies
  metrics:
    enabled: true

consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true

datasources:
  default:
    url: 'jdbc:h2:mem:multimedia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

r2dbc:
  datasources:
    default:
      url: 'r2dbc:h2:mem:///multimedia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
      driver: h2
      username: sa
      password: ''

micrometer:
  observation:
    http:
      client:
        enabled: true
      server:
        enabled: true

