micronaut:
  application:
    name: gateway
  server:
    port: 8181

consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true

kafka:
  bootstrap:
    servers: localhost:29092

