micronaut:
  application:
    name: movies
  metrics:
    enabled: true
  caches:
    moviesCache:
      maximum-size: 50
      expire-after-write: 10m
    movieCache:
      maximum-size: 5
      expire-after-write: 30m
    directorMoviesCache:
      maximum-size: 20
      expire-after-write: 15m
  logging:
    levels:
      com.akfc.training.filters: DEBUG

consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true

datasources:
  default:
    url: 'jdbc:h2:mem:multimedia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

r2dbc:
  datasources:
    default:
      url: 'r2dbc:h2:mem:///multimedia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
      driver: h2
      username: sa
      password: ''
      schema-generate: CREATE_DROP
      dialect: H2

micrometer:
  observation:
    http:
      client:
        enabled: true
      server:
        enabled: true

movies:
  title: "Best Movies"
  description: "Movies API"
